### ISSUE TITLE
TSLint errors point to temp files

### ISSUE THREAD

**Issue by electric-ladyland** [w0rp/ale#1210]
## Information

**VIM version**

![vv](https://user-images.githubusercontent.com/32247136/33800327-a60a307a-dd0b-11e7-87b3-0dd384ad3139.png)

Operating System: Windows 10 64bit

### :ALEInfo
```
  Current Filetype: typescript
Available Linters: ['eslint', 'tslint', 'tsserver', 'typecheck']
  Enabled Linters: ['tslint', 'tsserver']
 Linter Variables:

let g:ale_typescript_tslint_config_path = ''
let g:ale_typescript_tslint_executable = 'tslint'
let g:ale_typescript_tslint_ignore_empty_files = 0
let g:ale_typescript_tslint_rules_dir = ''
let g:ale_typescript_tslint_use_global = 0
let g:ale_typescript_tsserver_config_path = ''
let g:ale_typescript_tsserver_executable = 'tsserver'
let g:ale_typescript_tsserver_use_global = 0
 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 0
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {'vim': ['vint'], 'typescript': ['tsserver', 'tslint'], 'markdown': ['proselint'], 'json': ['jsonlint'], 'html': [], 'javascript': ['eslint'], 'yaml': ['yamllint'], 'text': ['proselint']}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 0
let g:ale_set_quickfix = 1
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = 'Γû¬'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = 'Γû½'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) C:\Users\Personal\Development\app\ui\node_modules\.bin\tslint
(finished - exit code 0) 'cmd /c cd C:\Users\Personal\Development\app\ui\src\app && C:\Users\Personal\Development\app\ui\node_modules\.bin\tslint --format json -c C:\Users\Personal\Development\app\ui\tslint.json C:\Users\Personal\AppData\Local\Temp\VIC5714.tmp\app-error-handler.ts'

<<<OUTPUT STARTS>>>
[]
<<<OUTPUT ENDS>>>

(started) 'cmd /c C:\Users\Personal\Development\app\ui\node_modules\.bin\tsserver'
(finished - exit code 0) 'cmd /c cd C:\Users\Personal\Development\app\ui\src\app && C:\Users\Personal\Development\app\ui\node_modules\.bin\tslint --format json -c C:\Users\Personal\Development\app\ui\tslint.json C:\Users\Personal\AppData\Local\Temp\VID7D0E.tmp\app-error-handler.ts'

<<<OUTPUT STARTS>>>
[]
<<<OUTPUT ENDS>>>

(finished - exit code 2) 'cmd /c cd C:\Users\Personal\Development\app\ui\src\app && C:\Users\Personal\Development\app\ui\node_modules\.bin\tslint --format json -c C:\Users\Personal\Development\app\ui\tslint.json C:\Users\Personal\AppData\Local\Temp\VIE8DD8.tmp\app-error-handler.ts'

<<<OUTPUT STARTS>>>
[{"endPosition":{"character":15,"line":32,"position":1102},"failure":"missing whitespace","name":"../../../../../AppData/Local/Temp/VIE8DD8.tmp/app-error-handler.ts","ruleName":"one-line","ruleSeverity":"ERROR","startPosition":{"character":15,"line":32,"position":1102}},{"endPosition":{"character":59,"line":32,"position":1146},"failure":"missing whitespace","name":"../../../../../AppData/Local/Temp/VIE8DD8.tmp/app-error-handler.ts","ruleName":"one-line","ruleSeverity":"ERROR","startPosition":{"character":59,"line":32,"position":1146}}]
<<<OUTPUT ENDS>>>

(finished - exit code 0) 'cmd /c cd C:\Users\Personal\Development\app\ui\src\app && C:\Users\Personal\Development\app\ui\node_modules\.bin\tslint --format json -c C:\Users\Personal\Development\app\ui\tslint.json C:\Users\Personal\AppData\Local\Temp\VIFC0D0.tmp\app-error-handler.ts'

<<<OUTPUT STARTS>>>
[]
<<<OUTPUT ENDS>>>

(finished - exit code 0) 'cmd /c cd C:\Users\Personal\Development\app\ui\src\app && C:\Users\Personal\Development\app\ui\node_modules\.bin\tslint --format json -c C:\Users\Personal\Development\app\ui\tslint.json C:\Users\Personal\AppData\Local\Temp\VIGDEA9.tmp\app-error-handler.ts'

<<<OUTPUT STARTS>>>
[]
<<<OUTPUT ENDS>>>

(finished - exit code 0) 'cmd /c cd C:\Users\Personal\Development\app\ui\src\app && C:\Users\Personal\Development\app\ui\node_modules\.bin\tslint --format json -c C:\Users\Personal\Development\app\ui\tslint.json C:\Users\Personal\AppData\Local\Temp\VIHF540.tmp\app-error-handler.ts'

<<<OUTPUT STARTS>>>
[]
<<<OUTPUT ENDS>>>

(finished - exit code 2) 'cmd /c cd C:\Users\Personal\Development\app\ui\src\app && C:\Users\Personal\Development\app\ui\node_modules\.bin\tslint --format json -c C:\Users\Personal\Development\app\ui\tslint.json C:\Users\Personal\AppData\Local\Temp\VIK1F8E.tmp\app-error-handler.ts'

<<<OUTPUT STARTS>>>
[{"endPosition":{"character":25,"line":46,"position":1383},"failure":"if statements must be braced","name":"../../../../../AppData/Local/Temp/VIK1F8E.tmp/app-error-handler.ts","ruleName":"curly","ruleSeverity":"ERROR","startPosition":{"character":0,"line":46,"position":1358}},{"endPosition":{"character":3,"line":46,"position":1361},"failure":"missing whitespace","fix":{"innerStart":1360,"innerLength":0,"innerText":" "},"name":"../../../../../AppData/Local/Temp/VIK1F8E.tmp/app-error-handler.ts","ruleName":"whitespace","ruleSeverity":"ERROR","startPosition":{"character":2,"line":46,"position":1360}}]
<<<OUTPUT ENDS>>>

```

## What went wrong

TSLint errors are pointing to some AppData/Local/Temp copies of the files I am editing.

## Reproducing the bug

Steps for repeating the bug:

1. Edit a TS file with Ale+TSLint and Ale errors showing in quickfix
2. Note the errors shown in quickfix are pointing to copies of the actual files being edited which are obviously not in the Temp folder.
![error](https://user-images.githubusercontent.com/32247136/33800341-017b9336-dd0c-11e7-9b97-b41895ab3ee2.png)

**Comment by w0rp** [comment]
Okay, give that another try. That should be fixed now.

**Comment by electric-ladyland** [comment]
Thank you for the very fast response time! Unfortunately I still see it after updating from master.

```
 Current Filetype: typescript
Available Linters: ['eslint', 'tslint', 'tsserver', 'typecheck']
  Enabled Linters: ['tslint', 'tsserver']
 Linter Variables:

let g:ale_typescript_tslint_config_path = ''
let g:ale_typescript_tslint_executable = 'tslint'
let g:ale_typescript_tslint_ignore_empty_files = 0
let g:ale_typescript_tslint_rules_dir = ''
let g:ale_typescript_tslint_use_global = 0
let g:ale_typescript_tsserver_config_path = ''
let g:ale_typescript_tsserver_executable = 'tsserver'
let g:ale_typescript_tsserver_use_global = 0
 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 0
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {'vim': ['vint'], 'typescript': ['tsserver', 'tslint'], 'markdown': ['proselint'], 'json': ['jsonlint'], 'html': [], 'javascript': ['eslint'], 'yaml': ['yamllint'], 'text': ['proselint']}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 0
let g:ale_set_quickfix = 1
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = 'Γû¬'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = 'Γû½'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) C:\Users\Personal\Development\app\ui\node_modules\.bin\tslint
(finished - exit code 2) 'cmd /c cd C:\Users\Personal\Development\app\ui\src\app && C:\Users\Personal\Development\app\ui\node_modules\.bin\tslint --format json -c C:\Users\Personal\Development\app\ui\tslint.json C:\Users\Personal\AppData\Local\Temp\VID5684.tmp\app-routing.module.ts'

<<<OUTPUT STARTS>>>
[{"endPosition":{"character":29,"line":50,"position":1411},"failure":"if statements must be braced","name":"../../../../../AppData/Local/Temp/VID5684.tmp/app-routing.module.ts","ruleName":"curly","ruleSeverity":"ERROR","startPosition":{"character":0,"line":50,"position":1382}},{"endPosition":{"character":3,"line":50,"position":1385},"failure":"missing whitespace","fix":{"innerStart":1384,"innerLength":0,"innerText":" "},"name":"../../../../../AppData/Local/Temp/VID5684.tmp/app-routing.module.ts","ruleName":"whitespace","ruleSeverity":"ERROR","startPosition":{"character":2,"line":50,"position":1384}}]
<<<OUTPUT ENDS>>>

(started) 'cmd /c C:\Users\Personal\Development\app\ui\node_modules\.bin\tsserver'
```

**Comment by w0rp** [comment]
I'll give it another try later, then.

**Comment by w0rp** [comment]
I have fixed this now. The problem was caused by a path issue only on Windows.

**Comment by electric-ladyland** [comment]
Works for me now. Thanks.
