### ISSUE TITLE
HTMLHint and flake8 doesn't lint when creating or opening a file

### ISSUE THREAD

**Issue by deathmaz** [w0rp/ale#154]
Hi @w0rp 
Here i recorded the issue https://asciinema.org/a/0n97nbmci590y3o6sek4s50l0

So first i created html file with empty `title` tag and no errors were displayed
Then i ran `htmlhint` on this file to show that `htmlhint` is actually works
After that i created `test.js` file with some errors and returned back to `test.html` file and as result ale start to display error.

After that i closed neovim and reopen `test.html` file and again ale didn't show any error. It start showing them only after i open `test.js` file and return back to `test.html`

``` sh
$ htmlhint -V
0.9.13

$ nvim -v
NVIM v0.1.6-175-g7246750
```

Thank you

**Comment by w0rp** [comment]
I think `BufReadPost` fires before the buffer is actually fully read. We might just have to increase the milliseconds delay for running linters when buffers are opened some more.

**Comment by deathmaz** [comment]
I noticed the same issue with flake8 for python

**Comment by w0rp** [comment]
I just pushed a commit to increase the delay for linting when a buffer is opened from 100ms to 300ms. Let me know if that fixes your issues.

**Comment by deathmaz** [comment]
I tried, but unfortunately the issue still persists.
Also i tried to increase the delay up to 1 second and it didn't help, so i don't think that the problem is in delay.

**Comment by deathmaz** [comment]
Hi @w0rp i'm closing this issue because i tried to reproduce it with minimal configuration and everything works fine so i guess there are some problems with my configuration and not with ale
Sorry for bothering with that and thank you for great plugin!

**Comment by w0rp** [comment]
I would be interested to know what configuration caused the issues you experienced, if you can find that out. I could put the information in the FAQ.

**Comment by deathmaz** [comment]
Sure, i will inform you when i find out
