### ISSUE TITLE
Autocomplete is too eager and inserts suggestions even when I haven't typed anything

### ISSUE THREAD

**Issue by joaqo** [w0rp/ale#1700]
## Information

**VIM version**

VIM - Vi IMproved 8.1 (2018 May 17, compiled May 18 2018 13:18:41)
macOS version

Operating System: macOS

### :ALEInfo

 Current Filetype: python
Available Linters: ['flake8', 'mypy', 'prospector', 'pycodestyle', 'pyflakes', 'pylint', 'pyls']
  Enabled Linters: ['pyls']
 Suggested Fixers:
  'add_blank_lines_for_python_control_statements' - Add blank lines before control statements.
  'autopep8' - Fix PEP8 issues with autopep8.
  'black' - Fix PEP8 issues with black.
  'isort' - Sort Python imports with isort.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'yapf' - Fix Python files with yapf.
 Linter Variables:
let g:ale_python_pyls_executable = 'pyls'
let g:ale_python_pyls_use_global = 0
 Global Variables:
let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 1
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 0
let g:ale_lint_on_text_changed = 1
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {'python': ['pyls']}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_list_vertical = 0
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 1
let g:ale_set_highlights = 0
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error = '•'
let g:ale_sign_info = '•'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '•'
let g:ale_sign_style_warning = '•'
let g:ale_sign_warning = '•'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:
(started) ['/bin/bash', '-c', '''/Users/joaqo/.virtualenvs/deleteme/bin/pyls''']

## What went wrong
ALE is too eager to autocomplete. So for example, I write the name of a python module, and as soon as I type `.` to start writing the name of a method of said module, ALE inserts the first method name  in the module, forcing me to delete said method name before I can start writing the method name I originally intended to write.

## Reproducing the bug

![sample](https://user-images.githubusercontent.com/14966348/42336982-b7d0f2c8-805b-11e8-9025-7e5b78858d3b.gif)

**Comment by w0rp** [comment]
That's a bug, it shouldn't be doing that. Could you share a project I can test this with? The completion results aren't inserted automatically like that for me.

**Comment by w0rp** [comment]
You might be able to work around this for now by adding `set completeopt+=noinsert ` to vimrc.

**Comment by joaqo** [comment]
Hey @w0rp thanks for the help.

The project is just a clean python virtualenv with `ipdb ipython python-language-server` installed, `time` is a standard library module in python.

Setting `set completeopt+=noinsert` didn't fix it. I suspect I may have something else seriously wrong in my config now.

**Comment by joaqo** [comment]
Nevermind setting `set completeopt+=noinsert` did fix it!

**Comment by w0rp** [comment]
Good to know. It should work without you having to do that, but at least you can do that for now. Hopefully I can somehow repeat the bug by tweaking a few things.

**Comment by w0rp** [comment]
@joaqo That can be fixed easily by checking `mode()`. What will be happening will be that the timer function is stopping after you've exited insert mode.

**Comment by joaqo** [comment]
@w0rp Thanks for the answer. Can't find what `mode()` is, do you mind sharing a link describing what it is? Tried running `:mode()` and searching for `mode` in the docs but came up empty handed.

**Comment by w0rp** [comment]
See `:help mode()`, but more importantly, see this commit for fixing that issue...

**Comment by w0rp** [comment]
If you `git pull` again, that issue should be fixed.

**Comment by joaqo** [comment]
@w0rp Thanks for the insanely fast commit to address the issue! Regrettably it didn't fix my issue :-( . Did the pull and verified the pulled files versus the commit you linked to, to make sure I had pulled them correctly and I had, but the issue persists.

**Comment by w0rp** [comment]
You'll have to play around with the code yourself in that case. I made it so the code for sending `Ctrl + x` then `Ctrl + o` is only run from Insert mode.

**Comment by Gyufei** [comment]
when I input a `.` ,  ale complete with the first suggestion word auto, then I setting `set completeopt+=noinsert` in my vimrc ,  fix this problem。but now  when i choose the first suggest word, I cant delete this word which after `.` anymore。
( I am so sad for my English and vim。

**Comment by w0rp** [comment]
I don't have the same issues myself. Try using a different version of Vim.

**Comment by w0rp** [comment]
That's for showing completions when you just type `.`. That's so a menu will appear when you type `foo.` and then it can offer `bar` for `foo.bar`, and so on. You should expect the menu to appear when you just type `.` on something. What you shouldn't expect is for some text to be entered without you making a selection, or for removing some characters to insert some text. If either of those happen for you, then that's a bug I can't repeat on any of my computers.

If you experience some issue where text is being inserted automatically, you'll have to debug the code yourself and see if you can fix it, as I can't repeat the bug.

**Comment by w0rp** [comment]
Let me know what your Vim version is. I could try installing the same version of Vim, and see if I can repeat the bug that way. Share your vimrc and generally any other information you can share.

**Comment by joaqo** [comment]
Just as a fyi I tried setting `set completeopt=menu,menuone,preview,noselect,noinsert` and using several different computers with different vim versions and the problem of ale confusing `some_key` + `esc` as `ctrl` + `o` persists. The only thing in common between these machines is my vimrc so thats probably the problem.

**Comment by w0rp** [comment]
@joaqo If you remove this line, does that particular problem go away? https://github.com/w0rp/ale/blob/a01fab2ee6dd827d555792f69fc30443a64dac5f/autoload/ale/completion.vim#L190

If so, can you add `:echom 'completion mode: ' . mode(1)` before that line and get the output by looking at `:mess`?

**Comment by joaqo** [comment]
Hey @w0rp, I'll go step by step on what I did:

- I tried in 2 ubuntu machines and 1 mac, the versions vary but they are all > 8
- Commented out `call ale#util#FeedKeys("\<C-x>\<C-o>", 'n') ` and it fixed the problem! One thing to note is that I was previously using `ctrl + n` for autocompleting, when I removed that line `ctrl + n` stopped working, but using `ctrl + x` + `ctrl + o` works just fine. Another thing to note is that the line you linked to was in line `182` instead of `190`, not sure if thats relevant at all.
- When I try adding `:echom 'completion mode: ' . mode(1)` as you instructed I only get `Messages maintainer: Bram Moolenaar <Bram@vim.org>` from running `:mess`.

Thanks a lot for the help!

**Comment by joaqo** [comment]
please ignore my comment about `ctrl + n` that only happened cause I was using a machine without `set completeopt=menu,menuone,preview,noselect,noinsert` in its vimrc.

**Comment by w0rp** [comment]
If `:echom` isn't working for you, could you try this line instead? `:call writefile([mode(1)], expand('~/mode.tmp'), 'a')`

Then share the contents of `~/mode.tmp`. I'm trying to figure out what mode Vim is in at the time that function is called for you.

**Comment by joaqo** [comment]
Ok, i got 
```
i
i
```
I think the reason :echom wasnt working is because I wasn't triggering an autocomplete in the file.

**Comment by w0rp** [comment]
I'm confused then. It looks like that's sending Ctrl+x Ctrl+o, without using any remapping, to open the omnicomplete menu only in Insert mode, so how does that end up moving your cursor around in normal mode?

**Comment by w0rp** [comment]
My best guess is that `feedkeys()` is queuing the keys for processing, and somehow executes after your key press to exit Insert mode. What I'll try to do instead is send a keypress for a custom `Plug` mapping which ends up sending `<C-x><C-o>`, and which will be `<Nop>` in normal mode.

**Comment by w0rp** [comment]
@joaqo Okay, try that.

**Comment by joaqo** [comment]
@w0rp Its fixed! Just pulled from master and everything looks good. Tried on a mac and an ubuntu machine, both fixed!

Thanks a lot for the great project and for the really fast help!

**Comment by malectro** [comment]
just noting that i had the same issue with automatic inserting with the most recent ale, and adding `set completeopt=menu,menuone,preview,noselect,noinsert` to my neovim `init.vim` fixed it. seems like there may be a race condition in overriding the value?

**Comment by w0rp** [comment]
@malectro Give that a go. I moved the temporary `compleopt` setting changes from before `feedkeys()` is fired to right before the key for opening the omnicomplete menu is read.

**Comment by malectro** [comment]
same issue if i remove the line from my config file. if you watch the whole gif here, you'll see that it's intermittent, which is weird.

![my issue](https://cl.ly/29011R3p1z0l/Screen%20Recording%202018-07-25%20at%2001.06%20PM.gif)

**Comment by w0rp** [comment]
Could you share all of your Vim configuration files and your Vim version?

**Comment by w0rp** [comment]
Okay, I pushed another commit. Try that. If that doesn't work, I don't know what will.

**Comment by joaqo** [comment]
I updated my version of ale, and removed `set completeopt=menu,menuone,preview,noselect,noinsert` from my vimrc to try out the fix, and the autocomplete problem persists.

This is just to give you some feedback, as it doesn't really affect me as adding `set completeopt=menu,menuone,preview,noselect,noinsert` to my vimrc completely fixes my problems.

Cheers!

**Comment by malectro** [comment]
yeah, verified that it's still happening. sorry, this sounds really frustrating.

**Comment by w0rp** [comment]
Okay, I'll just update the documentation telling people to set that option if they have this problem. I think this is a bug in Vim. Logically if you first set the option and second open the menu, you should expect Vim to respect the option you just set.

**Comment by DevonMorris** [comment]
I just saw this today with pyls. The noinsert option fixed it for me! Thanks!

**Comment by bangarangler** [comment]
I'm having this problem horribly writing JavaScript code. Been working on back end node js. And react client side. I've disabled everything trying to find the issue. Don't know what's going on but hope it gets fixed soon! Great plug in. Probably a vim change giving it issues. But it does make it almost unusable. I'll try the above fixes tomorrow and report back! Good luck everyone. May the odds be ever in our favor! 🤣

**Comment by bangarangler** [comment]
Ok update. After putting set completeopt+=noinsert in vim rc the annoyance has ended.  Thank you all for this thread. Have we yet figured out the actual culprit? Curiosity and what not.

**Comment by w0rp** [comment]
My guess is that there's a bug in Vim where settings applied from an asynchronous callback aren't applied until the callback exits, or something like that.

**Comment by Risto-Stevcev** [comment]
@w0rp I managed to replicate this issue consistently but in a different way. If you try to use ale with http://github.com/ajh17/VimCompletesMe and `let g:ale_completion_enabled = 1` then the issue shows up consistently when you work with javascript code

**Comment by w0rp** [comment]
Which version of Vim are you using? I think it's a bug in Vim, but I've never been able to create an isolated test case for it.

**Comment by Risto-Stevcev** [comment]
Could be, I'm using Neovim:

NVIM v0.3.5
Build type: Release

Operating System: Arch Linux

**Comment by Billy-** [comment]
This just randomly started happening to me, (OSX, NVIM 0.3.5).

Out of interest, what does the workaround, `set completeopt=menu,menuone,preview,noselect,noinsert`, do versus the default, and are there any changes/caveats in functionality to know about from it? I'm guessing it omits something?

🍻

**Comment by w0rp** [comment]
The default value for `completeopt` is `menu,preview`, meaning `insert,select` are present, and `menuone` isn't so menus aren't opened when there is a single result. ALE sets `menu,menuone,noselect,noinsert` and also `preview` if `preview` is already present in your options before starting omnicompletion with `<C-x><C-o>`. Sometimes it seems like Vim doesn't recognise the modified settings.  I think it's a bug in Vim, as I can't see anything logically wrong with the code, but I've never been able to create a simple script that repeats the bug. You can set the same settings to always be set that way, and that seems to fix the problem.

**Comment by Billy-** [comment]
Awesome, thanks for explaining 😄

**Comment by Risto-Stevcev** [comment]
Since it's kind of an elusive bug and there's already a workaround for it, I think it's worth it to add a section about it in the README describing that if you get it then just add ` set completeopt+=noinsert`

**Comment by w0rp** [comment]
It's mentioned in the help text. See `:h ale-completion-completeopt-bug`

**Comment by Risto-Stevcev** [comment]
Ah ok

**Comment by w0rp** [comment]
@matsuhav made a great suggestion in #3205, which I have now implemented. This should make completion in ALE work a little bit better by default.

**Comment by erikw** [comment]
I get a very weird behavior only when editing inside a word in the buffer and there is a completion string matching the left part of the cursor. Then suddenly what is to the right of the cursor is coped and inserted indefinitely, until I press `esc`.

I've had this behavior for several weeks but only tracked it down today. I found that when I remove the `longest` option for `completeopt`, then this bug is not happening. See the video where I replace 3 characters from the cursor and start typing a few characters `three`. When I press `esc` it stops inserting.

https://user-images.githubusercontent.com/175286/145677854-98c55787-3415-4f5b-9db1-153f347bc453.mov

@w0rp I wonder, is this the same bug that is already discovered in this bug report, or is this a separate new one?


Versions:
* nvim `v0.6.0` and the exact same bug for vim `8.2`
* Ale at master current head (b9744076a1603b37bc861e1aa885bbc052e0ed63)
* OS: macOS `12.0.1`
* Relevant  config part
  ```viml
  let g:ale_completion_autoimport = 1
  set omnifunc=ale#completion#OmniFunc
  set completeopt=menu,preview,longest
  ```

In this example I edit a ruby file for which solargraph lsp-server is used:

```viml
let g:ale_linters = {
		\ 'ruby': ['solargraph'],
		\ }
" }

" Fixing {
let g:ale_fixers = {
	\ '*': ['prettier'],
	\ 'ruby': ['rubocop'],
	\}
```
