### ISSUE TITLE
ALE interference with 'timeoutlen'-based "micro modes" (as used by BufMRU plugin)

### ISSUE THREAD

**Issue by drmikehenry** [w0rp/ale#1875]
## Information

**VIM version**

VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug 17 2018 08:18:47)
Included patches: 1-290

Operating System: Ubuntu 16.04 64-bit

## What went wrong

Under certain circumstances, ALE interferes with in-progress key mappings in
ways described below.  I noticed this while using the BufMRU plugin
(https://www.vim.org/scripts/script.php?script_id=2346), but I've reproduced the
symptoms with a Vim configuration containing only ALE itself and the small vimrc
below.

BufMRU uses a technique sometimes called a "micro mode" to reduce the number of
keystrokes needed to repeat an operation.  The `<Space>` key is mapped to Vim's
built-in `<C-^>` operation to edit the alternate file and to some additional
characters that place Vim into a micro mode where certain other keys have the
effect of being temporarily mapped.  This can be illustrated by the simplified
set of mappings below:

```p viml
map <Space>         <C-^>PENDING
map PENDING<Space>  <C-^>PENDING
map PENDINGf        :echo 'Forward!'<CR>PENDING
map PENDINGb        :echo 'Backward!'<CR>PENDING
map PENDING         <Nop>
```

When `<Space>` is pressed, it maps to `<C-^>` (to switch buffers) followed by
`PENDING`.  The string `PENDING` is a prefix of additional mappings, so Vim
waits for the next keypress to determine how to interpret the mapping.  If
`<Space>` is pressed again, another buffer switch is performed and the micro
mode is continued via another `PENDING` string.  If `f` or `b` is pressed next,
Vim uses the mapping for `PENDINGf` or `PENDINGb` to echo `Forward!` or
`Backward!` and the micro mode is continued.  On any other keypress, Vim applies
the mapping for `PENDING` (which is a `<Nop>`) to effectively exit the micro
mode.

In addition, if no key is pressed within `timeoutlen` seconds, Vim stops waiting
for additional keys and interprets any pending keystrokes as they are.  In the
above example, this means `PENDING` become `<Nop>`, exiting the micro mode after
a timeout.

When using this technique with ALE, somehow the micro mode is being exited
early, possibly due to a short-circuiting of the timeout.  Below is a complete
example showing the behavior.

## Reproducing the bug

To reproduce the behavior, start with a completely empty Vim configuration:
```p sh
rm -rf ~/.vimrc ~/.vim
```

Create `~/.vim/` containing a small `vimrc` file and the ALE plugin:
```p sh
mkdir -p ~/.vim/bundle
git clone https://github.com/w0rp/ale.git ~/.vim/bundle/ale
cat <<'EOF' > ~/.vim/vimrc
set nocompatible
set showcmd
set timeoutlen=20000
set rtp^=$HOME/.vim/bundle/ale

map <Space>         <C-^>PENDING
map PENDING<Space>  <C-^>PENDING
map PENDINGf        :echo 'Forward!'<CR>PENDING
map PENDINGb        :echo 'Backward!'<CR>PENDING
map PENDING         <Nop>

filetype on
syntax on
EOF
```

Create some sample shell script files (chosen because there is built-in support
for shell scripts):
```p sh
cat <<'EOF' > bad1.sh
#!/bin/sh

x="bad1
EOF
cat <<'EOF' > bad2.sh
#!/bin/sh

x="bad2
EOF
```

First, use Console Vim to demonstrate the micro mode working:
```p sh
vim bad1.sh bad2.sh
```

Now press `:n<CR>` to move to `bad2.sh` and press `<Space>` to switch back to
`bad1.sh` and begin the micro mode.  The word `PENDING` will appear on the right
side of the Vim status line while the micro mode is active.  Pressing `<Space>`
within the 20-second `timeoutlen` timeout will switch buffers and restart the
micro mode timeout, and pressing `f` or `b` will echo messages and continue the
micro mode.  Pressing other keys (e.g., `<Enter>`) will exit the micro mode.

Next, use GVim to demonstrate the failure condition:
```p sh
gvim bad1.sh bad2.sh
```

Now press `:n<CR>` to move to `bad2.sh` and press `<Space>` to switch back to
`bad1.sh` and attempt to begin the micro mode.  Though each press of `<Space>`
switches buffers, the word `PENDING` does not appear on the right, and `f` and
`b` do not perform their micro-mode jobs.

For some reason, moving the cursor down one line such that the cursor is on
different lines in `bad1.sh` and `bad2.sh` causes things to work again.

Is there anything ALE might be doing that could short-circuit the mapping
timeout?  I don't understand the inner workings of ALE and GVim well enough to
see what's going on, but perhaps you might have some ideas.

Thanks for any insight you might have into this unfortunate interaction.

**Comment by w0rp** [comment]
I pushed a commit to only echo if `mode(1) is# 'n'`. Try to repeat the bug again and let me know if that fixed it. If not, I have another idea.

**Comment by w0rp** [comment]
Nah, that would take too much time. I just skipped straight to what the problem is likely to be. I pushed a commit for my second idea. Try again.

**Comment by drmikehenry** [comment]
Unfortunately this second patch doesn't fix the problem either.  I don't think Vim is in operator-pending mode in this case; the string `PENDING` is just a sequence of characters that happens to be a prefix of a normal-mode mapping (`PENDINGf`, for example), so Vim is waiting in Normal mode for more keystrokes to determine how to interpret the mappings.

**Comment by w0rp** [comment]
Why don't you just use regular keybindings instead of this crazy business with mapping a sequence of keys to NOP?

**Comment by w0rp** [comment]
```vim
:noremap <Space> <Nop>
:noremap <Space>f <C-^>
```

You can do basically what you want like that.

**Comment by drmikehenry** [comment]
I'm trying to use plugins like BufMRU that use this "micro mode" technique as part of their operation.  To make an easy-to-reproduce example that doesn't require installation or knowledge of BufMRU, I've extracted the portion of BufMRU that demonstrates the problem.  The idea of a micro mode is to allow a (possibly long) key sequence to initiate the mode (`<Space>` is that sequence in this example, but it may be longer in general).  Once the mode has been entered, very short (single-character, in this case) temporary mappings are applied that allow easy repetition.  For BufMRU, these single characters are `f` and `b`.  Pressing `<Space>` initiates BufMRU mode and switches to the most recently used buffer; until 'timeoutlen' expires, pressing `f` goes to the next-most-recently-used buffer.  This provides a means to browse through the most recently used buffers in a way I find very convenient.  I use other plugins with this same micro mode concept; for example, to change font size I press the three-key sequence `\\+` to increment by one point and enter a micro mode which defines `+` and `-` to continue incrementing or decrementing the font size without the need to press a longer sequence such as `\\+`.

If you run the example mappings, you'll see that pressing `<Space>` enters a micro mode in which `f` and `b` can be pressed with no prefix; for a demo, these mappings just echo some strings, but you can imagine them flipping through a most-recently-used buffer history maintained by the BufMRU plugin.

Short, unused key mappings are rare.  There aren't enough of them to provide single-key mappings for everything I'd like to do.  The micro mode technique allows single-key mappings that are only temporarily defined while the mode is active, allowing reuse of these short mappings for different purposes at different times.

**Comment by w0rp** [comment]
It's not how you should map key sequences in Vim. You should define a mapping for a sequence of keys with `:noremap abc` for keys `a`, `b`, and `c`. I wouldn't be surprised if this hack you're using doesn't work. I recommend changing `g:ale_lint_on_text_changed` to something like `'insert'` so normal mode keypresses don't trigger ALE linting. That might avoid the problem you're having.

**Comment by drmikehenry** [comment]
I'm now able to reproduce this problem without ALE.  The symptoms can be reproduced with the below script named `map_timeout.vim`:

    map <silent> \12  :echo 'Got \12'<CR>
    map <silent> \123  :echo 'Got \123'<CR>

    set timeoutlen=10000

    function! Timer(timerId)
        echo 'Timer expired'
    endfunction

    function! ExitCallback(job, status)
        call timer_start(3000, 'Timer')
    endfunction

    command! StartJob let jobid = job_start(
            \ 'python -c "import time; time.sleep(3)',
            \ {
            \     'exit_cb': 'g:ExitCallback',
            \ })

After `:source map_timeout.vim`, press `\12`.  Vim waits for more input because it's ambiguous which of the two maps (`\12` or `\123`) is wanted; if no keys are pressed for ten seconds, Vim times out and executes the `\12` mapping.  If `3` is pressed before timeout, the `\123` map is executed.  If any other key is pressed before timeout, Vim executes the `\12` map and then processes that other key normally.  This is Vim's standard mapping behavior which underlies the "micro mode" technique.

To demonstrate the problem, first execute `:StartJob` to begin the three-second sleep job, then press `\12`.  For three seconds, Vim will keep the `\12` pending, but when the job completes, the `ExitCallback` function starts a timer.  In Console Vim, things continue to work as expected, and nothing happens until the remaining seven seconds expire, at which point the `\12` mapping will execute; but in the GUI, there is different logic that aborts the mapping timeout when the timer is started, causing the `\12` mapping to execute after only three seconds.

It's not clear to me why the GUI input logic was changed without also changing the console input logic.  The change was added in Vim 7.4.1873: https://github.com/vim/vim/commit/4231da403e3c879dd6ac261e51f4ca60813935e3

With unlucky timing, any multi-key mapping might be aborted by the completion of an ALE job that starts a timer (but only for GUI users; console users are immune to this problem).

I'm planning to inquire about fixing Vim so that starting timers from job callbacks won't abort in-progress mappings, since it seems too restrictive to demand that plugin authors avoid setting timers from job callbacks.

Thanks for your help with this problem.

**Comment by w0rp** [comment]
Okay, makes sense. This bug can be fixed in Vim.

**Comment by drmikehenry** [comment]
Update: Vim 8.1.0834 fixes the bug which causes mapping failures as described in this ticket.

**Comment by w0rp** [comment]
Good to know. Thanks for the update. :+1:
