### ISSUE TITLE
Rubocop doesn't seem to be running

### ISSUE THREAD

**Issue by jtmkrueger** [w0rp/ale#287]
I know the gem is installed, because I can run it from the command line and it works just fine. Ale is working on js files just fine, but I never see rubocop run. I've been testing in a file that I know should kick off some errors and warnings.

I'm not sure what additional information I can give, other than rubocop versions 0.47.1, 0.40.0 and 0.28.0 are installed. I don't have any specific settings set for ale.

**Comment by jtmkrueger** [comment]
I keep seeing this pop up when I dump the logs
```
line 12: sourcing "/Users/jkrueger/.vim/bundle/ale/ale_linters/ruby/rubocop.vim"
Searching for "autoload/ale_linters/ruby/rubocop.vim" in "/Users/jkrueger/.vim,/Users/jkrueger/.vim/bundle/vundle,/Users/jkrueger/.vim/bundle/vim-coffee-script,/Users/jkrueger/.vim/bundle/vim-javascript-syntax,/Users/jkrueger/.vim/bundle/scss-syntax.vim,/Users/jkrueger/.vim/bundle/vim-ruby,/Users/jkrueger/.vim/bundle/vim-mustache-handlebars,/Users/jkrueger/.vim/bundle/javascript-libraries-syntax.vim,/Users/jkrueger/.vim/bundle/vim-jst,/Users/jkrueger/.vim/bundle/vim-tmux,/Users/jkrueger/.vim/bundle/vim-hybrid,/Users/jkrueger/.vim/bundle/vim-colors-solarized,/Users/jkrueger/.vim/bundle/vim-c-cr,/Users/jkrueger/.vim/bundle/ack.vim,/Users/jkrueger/.vim/bundle/ale,/Users/jkrueger/.vim/bundle/YouCompleteMe,/Users/jkrueger/.vim/bundle/vim-flow,/Users/jkrueger/.vim/bundle/rainbow,/Users/jkrueger/.vim/bundle/vim-misc,/Users/jkrueger/.vim/bundle/vim-easytags,/Users/jkrueger/.vim/bundle/tagbar,/Users/jkrueger/.vim/bundle/vim-airline,/Users/jkrueger/.vim/bundle/vim-airline-themes,/Users/jkrueger/.vim/bundle/vim-bufonly,
Searching for "/Users/jkrueger/.vim/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vundle/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-coffee-script/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-javascript-syntax/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/scss-syntax.vim/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-ruby/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-mustache-handlebars/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/javascript-libraries-syntax.vim/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-jst/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-tmux/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-hybrid/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-colors-solarized/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-c-cr/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/ack.vim/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/ale/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/YouCompleteMe/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-flow/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/rainbow/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-misc/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-easytags/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/tagbar/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-airline/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-airline-themes/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-bufonly/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-gitgutter/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/emmet-vim/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-togglecursor/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-diminactive/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/delimitMate/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-cursorword/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-repeat/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-vinegar/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-rails/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-surround/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-fugitive/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-commentary/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-endwise/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/usr/local/Cellar/macvim/8.0-119_1/MacVim.app/Contents/Resources/vim/vimfiles/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/usr/local/Cellar/macvim/8.0-119_1/MacVim.app/Contents/Resources/vim/runtime/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/usr/local/Cellar/macvim/8.0-119_1/MacVim.app/Contents/Resources/vim/vimfiles/after/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/after/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/Vundle.vim/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vundle/after/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-coffee-script/after/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-javascript-syntax/after/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/scss-syntax.vim/after/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-ruby/after/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-mustache-handlebars/after/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/javascript-libraries-syntax.vim/after/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-jst/after/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-tmux/after/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-hybrid/after/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-colors-solarized/after/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-c-cr/after/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/ack.vim/after/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/ale/after/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/YouCompleteMe/after/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-flow/after/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/rainbow/after/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-misc/after/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-easytags/after/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/tagbar/after/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-airline/after/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-airline-themes/after/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-bufonly/after/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-gitgutter/after/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/emmet-vim/after/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-togglecursor/after/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-diminactive/after/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/delimitMate/after/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-cursorword/after/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-repeat/after/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-vinegar/after/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-rails/after/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-surround/after/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-fugitive/after/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-commentary/after/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-endwise/after/autoload/ale_linters/ruby/rubocop.vim"
not found in 'runtimepath': "autoload/ale_linters/ruby/rubocop.vim"
finished sourcing /Users/jkrueger/.vim/bundle/ale/ale_linters/ruby/rubocop.vim
continuing in function ale#Queue[11]..ale#linter#Get[20]..ale#linter#GetAll
Searching for "/Users/jkrueger/.vim/bundle/YouCompleteMe/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-flow/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/rainbow/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-misc/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-easytags/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/tagbar/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-airline/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-airline-themes/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-bufonly/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-gitgutter/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/emmet-vim/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-togglecursor/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-diminactive/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/delimitMate/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-cursorword/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-repeat/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-vinegar/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-rails/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-surround/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-fugitive/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-commentary/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-endwise/ale_linters/ruby/*.vim"
Searching for "/usr/local/Cellar/macvim/8.0-119_1/MacVim.app/Contents/Resources/vim/vimfiles/ale_linters/ruby/*.vim"
Searching for "/usr/local/Cellar/macvim/8.0-119_1/MacVim.app/Contents/Resources/vim/runtime/ale_linters/ruby/*.vim"
Searching for "/usr/local/Cellar/macvim/8.0-119_1/MacVim.app/Contents/Resources/vim/vimfiles/after/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/after/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/Vundle.vim/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/vundle/after/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-coffee-script/after/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-javascript-syntax/after/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/scss-syntax.vim/after/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-ruby/after/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-mustache-handlebars/after/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/javascript-libraries-syntax.vim/after/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-jst/after/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-tmux/after/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-hybrid/after/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-colors-solarized/after/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-c-cr/after/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/ack.vim/after/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/ale/after/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/YouCompleteMe/after/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-flow/after/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/rainbow/after/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-misc/after/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-easytags/after/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/tagbar/after/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-airline/after/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-airline-themes/after/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-bufonly/after/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-gitgutter/after/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/emmet-vim/after/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-togglecursor/after/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-diminactive/after/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/delimitMate/after/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-cursorword/after/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-repeat/after/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-vinegar/after/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-rails/after/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-surround/after/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-fugitive/after/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-commentary/after/ale_linters/ruby/*.vim"
Searching for "/Users/jkrueger/.vim/bundle/vim-endwise/after/ale_linters/ruby/*.vim"
Executing BufRead Auto commands for "*"
```

Is there an additional file(s) I need to install to get things to work right?

**Comment by mcmillion** [comment]
I'm seeing the same thing in logs. Again, `rubocop` works fine in CLI and other linters like `jshint` work just fine in ale. I installed via Plug and I've confirmed that the `rubocop.vim` file is there in a location that it's searching. On my system, the file exists in the location where it's attempting to source from, but it never seems to actually find it?

```
line 12: sourcing "/Users/Matthew/.vim/plugged/ale/ale_linters/ruby/rubocop.vim"
Searching for "autoload/ale_linters/ruby/rubocop.vim" in "/Users/Matthew/.vim,/Users/Matthew/.vim/plugged/ultisnips/,/Users/Matthew/.vim/plugged/vim-gitgutter/,/Users/Matthew/.vim/plugged/vim-colors-solarized/,/Users/Matthew/.fzf/,/Users/Matthew/.vim/plugged/fzf.vim/,/Users/Matthew/.vim/plugged/emmet-vim/,/Users/Matthew/.vim/plugged/vim-polyglot/,/Users/Matthew/.vim/plugged/vim-commentary/,/Users/Matthew/.vim/plugged/vim-endwise/,/Users/Matthew/.vim/plugged/vim-fugitive/,/Users/Matthew/.vim/plugged/vim-obsession/,/Users/Matthew/.vim/plugged/vim-rails/,/Users/Matthew/.vim/plugged/vim-repeat/,/Users/Matthew/.vim/plugged/vim-surround/,/Users/Matthew/.vim/plugged/vim-unimpaired/,/Users/Matthew/.vim/plugged/vim-vinegar/,/Users/Matthew/.vim/plugged/vim-airline/,/Users/Matthew/.vim/plugged/vim-airline-themes/,/Users/Matthew/.vim/plugged/ferret/,/Users/Matthew/.vim/plugged/ale/,/usr/local/share/vim/vimfiles,/usr/local/share/vim/vim80,/usr/local/share/vim/vimfiles/after,/Users/Matthew/.vim/plugged/ultisnips/after,/Use
Searching for "/Users/Matthew/.vim/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/Matthew/.vim/plugged/ultisnips/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/Matthew/.vim/plugged/vim-gitgutter/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/Matthew/.vim/plugged/vim-colors-solarized/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/Matthew/.fzf/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/Matthew/.vim/plugged/fzf.vim/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/Matthew/.vim/plugged/emmet-vim/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/Matthew/.vim/plugged/vim-polyglot/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/Matthew/.vim/plugged/vim-commentary/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/Matthew/.vim/plugged/vim-endwise/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/Matthew/.vim/plugged/vim-fugitive/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/Matthew/.vim/plugged/vim-obsession/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/Matthew/.vim/plugged/vim-rails/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/Matthew/.vim/plugged/vim-repeat/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/Matthew/.vim/plugged/vim-surround/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/Matthew/.vim/plugged/vim-unimpaired/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/Matthew/.vim/plugged/vim-vinegar/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/Matthew/.vim/plugged/vim-airline/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/Matthew/.vim/plugged/vim-airline-themes/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/Matthew/.vim/plugged/ferret/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/Matthew/.vim/plugged/ale/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/usr/local/share/vim/vimfiles/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/usr/local/share/vim/vim80/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/usr/local/share/vim/vimfiles/after/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/Matthew/.vim/plugged/ultisnips/after/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/Matthew/.vim/plugged/vim-polyglot/after/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/Users/Matthew/.vim/after/autoload/ale_linters/ruby/rubocop.vim"
Searching for "/usr/local/Cellar/vim/8.0.0243/share/vim/vim80/pack/dist/opt/matchit/autoload/ale_linters/ruby/rubocop.vim"
not found in 'runtimepath': "autoload/ale_linters/ruby/rubocop.vim"
```

**Comment by yous** [comment]
I just have found that `l:pattern` for RuboCop error string is wrong. For me, it works when I modify `ale/ale_linters/ruby/rubocop.vim` like this:

``` diff
diff --git a/ale_linters/ruby/rubocop.vim b/ale_linters/ruby/rubocop.vim
index 69d26d3..f055faf 100644
--- a/ale_linters/ruby/rubocop.vim
+++ b/ale_linters/ruby/rubocop.vim
@@ -6,7 +6,7 @@ function! ale_linters#ruby#rubocop#Handle(buffer, lines) abort
     "
     " <path>/_:47:14: 83:29: C: Prefer single-quoted strings when you don't
     " need string interpolation or special symbols.
-    let l:pattern = '\v_:(\d+):(\d+): (.): (.+)'
+    let l:pattern = '\v:(\d+):(\d+): (.): (.+)'
     let l:output = []

     for l:line in a:lines
```

**Comment by mcmillion** [comment]
This totally fixes it. You should submit a quick PR and I'll vouch.

**Comment by yous** [comment]
Yes, I submitted #293.

**Comment by derekprior** [comment]
Apologies for the screw up there. I don't think this is the only issue with my earlier change. I addressed another issue in #299.

**Comment by w0rp** [comment]
This should be resolved now.

**Comment by jayniz** [comment]
For me, rubocop still doesn't lint (others like eslint do). My env:

- ale: current master (f6bc73b749f28b31500716710429738afa9d6bc9)
- rubocop: 0.39.0 (works via CLI)
- NVIM: 0.1.7 (via homebrew)
- ruby: 2.3.3p222 (via rbenv)
- MacOS: Sierra 10.12.3

**Comment by w0rp** [comment]
Could you paste your path to `rubocop`, and some example output from the CLI for `rubocop --format emacs --force-exclusion --stdin whatever_filename` where there are errors and warnings?

**Comment by jayniz** [comment]
Sorry for the confusion, @w0rp, my rubocop version somehow was super old. With `0.47.1` it works fine. 👍

**Comment by w0rp** [comment]
Aha! I think it would be a good thing to echo some kind of warning if the version is too old. I'll open an issue for that.
