### ISSUE TITLE
Detect import paths for mypy

### ISSUE THREAD

**Issue by w0rp** [w0rp/ale#363]
This issue tracks #324 for `mypy`. My thoughts will be gathered here.

- The configuration file for `mypy` can be named either `setup.cfg` or `mypy.ini`. `mypy.ini` takes precedence.
- `mypy` doesn't search in ancestor directories for configuration files, like say `eslint` does. The location for the file has to be specified manually.
- Running `mypy` from the directory where `mypy.ini` lives does automatically use that file.
- `mypy` versions 0.4.5 and above support a `mypy_path` option inside of the configuration file.
- Version 0.4.5 was released on November 2016.

**Comment by w0rp** [comment]
I think the best strategy for `mypy` might to be insist that a `mypy.ini` or `setup.cfg` file exists in the project root, where other Python modules are available, and then run `mypy` with the directory changed to run from that directory. I would take away the code which exists currently for finding a directory called `stubs`.

A section can be added to the documentation explaining how to configure `mypy` to get the best results.

**Comment by lgalke** [comment]
Hey w0rp,
I just discovered your plugin and I am trying it in favor of syntastic. So far it feels great, and made me also get curious about this mypy linter. Unfortunately, its performance inside vim is pretty poor.
One major issue I wanted to report (I am not sure whether this can be solved by mypy.ini alone):
It does not respect the file the error was found in:
My setting:

```sh
packageXY_root/some_executable.py
packageXY_root/packageXY/__init__.py
packageXY_root/packageXY/and.py
packageXY_root/packageXY/the.py
packageXY_root/packageXY/rest.py
```

Now of course, `some_executable.py` imports from `{and,the,rest}.py`, and to not raise Errors on some kind of missing import I immediately added the option:

``` vim
let g:ale_python_mypy_options = '--ignore-missing-imports'
```

But now the behaviour is even more strange:

`mypy` obviously descends into imported files on (command line) invocation of `mypy some_executable.py` and also reports errors in the other files:

```sh
packageXY/and.py:30: error: Name 'CombinatorMixin' already defined
packageXY/and.py:31: error: Name 'argtopk' already defined
packageXY/rest.py:9: error: Name 'RetrievalBase' already defined
packageXY/rest.py:9: error: Name 'RetriEvalMixin' already defined
```

Its okay since these errors are anticipated (try relative import, except: absolute import).

BUT: now back in ALE's invocation of `mypy` I get the error lines highlighted in the original `some_executable.py` file. More precise, I get line 9 in `some_executable.py` highlighted as error (and put in the loc list), while the error is clearly not in line 9 of this file but in line 9 of the other `packageXY/rest.py`.

I hope this fits here.

Best Regards,
lgalke

**Comment by w0rp** [comment]
I thought this might be an issue. If someone else doesn't work on it, I will be. There are two major issue with the linter.

1. It reports errors from the wrong files.
2. It probably needs to run against the file on disk, instead of against the Vim buffer like most other ALE linters.

The first issue is easier to fix. The second issue requires implementing #333 first, which I've been working on now and then over the past few weeks. I'm mostly in the exploratory phase of trying to figure out how to get it to work in a decent way. I've put some of my thoughts on that in the issue and on the wiki.

**Comment by w0rp** [comment]
Those issues are sort of in addition to the this GitHub issue.

I will eventually be using `mypy` at work, so I've got the impetus to get it working properly.

**Comment by lgalke** [comment]
The issue of multiple files is the same for `chktex` when invoked with `-I` (as in the default args)

**Comment by w0rp** [comment]
I'll open another issue for tracking that.

**Comment by kjyv** [comment]
At least for mypy, you could also pipe in program text with the -c option instead of a tmp file and in order to not receive errors from other files, there is the --follow-imports skip option. However, and I'd consider that a mypy bug, this option still complains if there is a relative imports in the source and the file is not found (e.g. in temp). But if you call mypy in the dir of the current buffer, pipe the buffer contents and set these options, it should be working ok.

**Comment by w0rp** [comment]
Thank you for the information. It sounds like `--follow-imports=silent` is a good option for only getting the errors for the current file.

**Comment by kjyv** [comment]
Yeah, I agree that's a good option. I'm not really sure why, but now linting works fine for me, including files that have relative imports. Calling mypy the same way ale does it even reports an error but it works fine from within vim.

**Comment by w0rp** [comment]
You probably haven't hit the issue there yet. I think I've seen it before myself. If no one else fixes it, I will, eventually.

**Comment by kjyv** [comment]
I would love to have the additional features that come with mypy looking into imported source files (checking return value type, argument types etc.) but I guess it's more clear to you what needs to be done in the code for that. As written, I'd suggest a temporary file within the same directory as the original.

**Comment by w0rp** [comment]
I plan to implement #333, and run `mypy` only against the file on disk instead. That should pretty much fix any import issues. Creating a temporary file will cause other problems, and might not work in the end.

**Comment by kjyv** [comment]
I guess it depends on the linter if a tempfile creates further issues (it seems golint behaves differently depending on the filename?). Mypy only seems to care about the path, not the name of the file (e.g. .filename.py.tmp works). I think it is a nice feature to have on the fly syntax and linter errors and it should at least stay an option - I don't see why linter errors would only be wanted on save and maybe syntax on the fly. In any case, the issue remains in which directory to call mypy as this applies to the proper saved file too. In my current case, for many files mypy modulepath/filename.py has to be called.

**Comment by w0rp** [comment]
Here is how to fix the module path problems.

1. Require a `mypy.ini` file to exist in the project root.
2. Find the project root by looking for the `mypy.ini` file.
3. Add `cd project_root_dir && ...` to the command which is run.

`mypy` will use the `mypy.ini` file in the directory it is run from, and that file can contain whatever module paths are needed with the `mypy_path` setting. Doing the above will use the correct configuration file, and fix pretty much all of the import issues.

I pretty much know how to fix this already, I'm just working on #333 first.

**Comment by w0rp** [comment]
Now the `mypy` linter will check the file on disk instead, and understands import paths. The virtualenv version of `mypy` will be used by default, when detected.

`mypy` can take quite a few seconds to return any results, so it's certainly not capable of being modified to check files on the fly at the moment, so checking on save should be okay for now.

**Comment by w0rp** [comment]
I also fixed the error handling, so only errors for the current file will be displayed.

**Comment by hjwp** [comment]
Hi  there, I _think_ i'm still seeing weird behaviour here.  the repro/condition is:

- base folder contains mypy.ini
- but it does _not_ contain any of the other files that mark a folder as being the right "python root" (no pytest.ini, setup.cfg, etc)

what happens:  ale finds the virtualenv mypy just fine, but it `cds` to a different directory (either a parent or a child, depending on which file is being linted, but one containing a pytest.ini in either case) when it runs mypy, which means the mypy.ini is ignored.

the fix might be to override `function! ale#python#FindProjectRoot` in favour of "whatever the location of mypy.ini is" for choosing the cwd of calls to mypy?

**Comment by w0rp** [comment]
Open a new issue for that.
