### ISSUE TITLE
Error markers remain after switching file

### ISSUE THREAD

**Issue by trygveaa** [w0rp/ale#528]
When I switch from one file to another the gutter updates immediately (either to nothing, or to the previous result) which is nice. However, the background color on the character that has the error remains from the previous file until the linters finish running for the current file.

Below is a gif which shows the problem. I switch between two files which each has one error, in different positions. Right after I switch file, the background on the character is the one from the previous file, instead of the one from the previous result which would have matched with the gutter.

![vim-ale-markers-remain](https://cloud.githubusercontent.com/assets/601966/25634649/acabf55a-2f7b-11e7-928a-b0ee65d507d3.gif)

Info from ALEInfo as requested:
>  Current Filetype: javascript.jsx
> Available Linters: ['eslint', 'flow', 'jscs', 'jshint', 'standard', 'xo']
>   Enabled Linters: ['eslint', 'flow', 'jscs', 'jshint', 'standard', 'xo']
>  Linter Variables:
> 
> let g:ale_javascript_eslint_executable = 'eslint'
> let g:ale_javascript_eslint_options = ''
> let g:ale_javascript_eslint_use_global = 0
> let g:ale_javascript_flow_executable = 'flow'
> let g:ale_javascript_flow_use_global = 0
> let g:ale_javascript_jshint_executable = 'jshint'
> let g:ale_javascript_jshint_use_global = 0
> let g:ale_javascript_standard_executable = 'standard'
> let g:ale_javascript_standard_options = ''
> let g:ale_javascript_standard_use_global = 0
> let g:ale_javascript_xo_executable = 'xo'
> let g:ale_javascript_xo_options = ''
> let g:ale_javascript_xo_use_global = 0
>  Global Variables:
> 
> let g:ale_echo_cursor = 1
> let g:ale_echo_msg_error_str = 'Error'
> let g:ale_echo_msg_format = '%s'
> let g:ale_echo_msg_warning_str = 'Warning'
> let g:ale_enabled = 1
> let g:ale_keep_list_window_open = 0
> let g:ale_lint_delay = 200
> let g:ale_lint_on_enter = 1
> let g:ale_lint_on_save = 1
> let g:ale_lint_on_text_changed = 'always'
> let g:ale_linter_aliases = {}
> let g:ale_linters = {}
> let g:ale_open_list = 0
> let g:ale_set_highlights = 1
> let g:ale_set_loclist = 1
> let g:ale_set_quickfix = 0
> let g:ale_set_signs = 1
> let g:ale_sign_column_always = 0
> let g:ale_sign_error = '>>'
> let g:ale_sign_offset = 1000000
> let g:ale_sign_warning = '--'
> let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
> let g:ale_warn_about_trailing_whitespace = 1
>   Command History:
> 
> (finished - exit code 1) ['/usr/bin/zsh', '-c', '/home/trygve/dev/test-ale/node_modules/eslint/bin/eslint.js  -f unix --stdin --stdin-filename /home/trygve/dev/test-ale/2.js < /tmp/vLE54RM/184/2.js']
> (finished - exit code 12) ['/usr/bin/zsh', '-c', '/home/trygve/dev/test-ale/node_modules/.bin/flow check-contents --respect-pragma --json --from ale /home/trygve/dev/test-ale/2.js < /tmp/vLE54RM/185/2.js']
> (finished - exit code 1) ['/usr/bin/zsh', '-c', '/home/trygve/dev/test-ale/node_modules/eslint/bin/eslint.js  -f unix --stdin --stdin-filename /home/trygve/dev/test-ale/2.js < /tmp/vLE54RM/188/2.js']
> (finished - exit code 12) ['/usr/bin/zsh', '-c', '/home/trygve/dev/test-ale/node_modules/.bin/flow check-contents --respect-pragma --json --from ale /home/trygve/dev/test-ale/2.js < /tmp/vLE54RM/189/2.js']
> (finished - exit code 1) ['/usr/bin/zsh', '-c', '/home/trygve/dev/test-ale/node_modules/eslint/bin/eslint.js  -f unix --stdin --stdin-filename /home/trygve/dev/test-ale/2.js < /tmp/vLE54RM/192/2.js']
> (finished - exit code 12) ['/usr/bin/zsh', '-c', '/home/trygve/dev/test-ale/node_modules/.bin/flow check-contents --respect-pragma --json --from ale /home/trygve/dev/test-ale/2.js < /tmp/vLE54RM/193/2.js']
> (finished - exit code 1) ['/usr/bin/zsh', '-c', '/home/trygve/dev/test-ale/node_modules/eslint/bin/eslint.js  -f unix --stdin --stdin-filename /home/trygve/dev/test-ale/2.js < /tmp/vLE54RM/196/2.js']
> (started) ['/usr/bin/zsh', '-c', '/home/trygve/dev/test-ale/node_modules/.bin/flow check-contents --respect-pragma --json --from ale /home/trygve/dev/test-ale/2.js < /tmp/vLE54RM/197/2.js']
> (finished - exit code 1) ['/usr/bin/zsh', '-c', '/home/trygve/dev/test-ale/node_modules/eslint/bin/eslint.js  -f unix --stdin --stdin-filename /home/trygve/dev/test-ale/2.js < /tmp/vLE54RM/200/2.js']
> (finished - exit code 12) ['/usr/bin/zsh', '-c', '/home/trygve/dev/test-ale/node_modules/.bin/flow check-contents --respect-pragma --json --from ale /home/trygve/dev/test-ale/2.js < /tmp/vLE54RM/201/2.js']
> (finished - exit code 1) ['/usr/bin/zsh', '-c', '/home/trygve/dev/test-ale/node_modules/eslint/bin/eslint.js  -f unix --stdin --stdin-filename /home/trygve/dev/test-ale/2.js < /tmp/vLE54RM/204/2.js']
> (started) ['/usr/bin/zsh', '-c', '/home/trygve/dev/test-ale/node_modules/.bin/flow check-contents --respect-pragma --json --from ale /home/trygve/dev/test-ale/2.js < /tmp/vLE54RM/205/2.js']
> (finished - exit code 1) ['/usr/bin/zsh', '-c', '/home/trygve/dev/test-ale/node_modules/eslint/bin/eslint.js  -f unix --stdin --stdin-filename /home/trygve/dev/test-ale/2.js < /tmp/vLE54RM/208/2.js']
> (finished - exit code 12) ['/usr/bin/zsh', '-c', '/home/trygve/dev/test-ale/node_modules/.bin/flow check-contents --respect-pragma --json --from ale /home/trygve/dev/test-ale/2.js < /tmp/vLE54RM/209/2.js']
> (finished - exit code 1) ['/usr/bin/zsh', '-c', '/home/trygve/dev/test-ale/node_modules/eslint/bin/eslint.js  -f unix --stdin --stdin-filename /home/trygve/dev/test-ale/2.js < /tmp/vLE54RM/212/2.js']
> (finished - exit code 12) ['/usr/bin/zsh', '-c', '/home/trygve/dev/test-ale/node_modules/.bin/flow check-contents --respect-pragma --json --from ale /home/trygve/dev/test-ale/2.js < /tmp/vLE54RM/213/2.js']
> (started) ['/usr/bin/zsh', '-c', '/home/trygve/dev/test-ale/node_modules/eslint/bin/eslint.js  -f unix --stdin --stdin-filename /home/trygve/dev/test-ale/2.js < /tmp/vLE54RM/216/2.js']
> (finished - exit code 12) ['/usr/bin/zsh', '-c', '/home/trygve/dev/test-ale/node_modules/.bin/flow check-contents --respect-pragma --json --from ale /home/trygve/dev/test-ale/2.js < /tmp/vLE54RM/217/2.js']
> (finished - exit code 1) ['/usr/bin/zsh', '-c', '/home/trygve/dev/test-ale/node_modules/eslint/bin/eslint.js  -f unix --stdin --stdin-filename /home/trygve/dev/test-ale/2.js < /tmp/vLE54RM/220/2.js']
> (finished - exit code 12) ['/usr/bin/zsh', '-c', '/home/trygve/dev/test-ale/node_modules/.bin/flow check-contents --respect-pragma --json --from ale /home/trygve/dev/test-ale/2.js < /tmp/vLE54RM/221/2.js']

**Comment by w0rp** [comment]
What commands are you using to change from one file to another?

**Comment by trygveaa** [comment]
I used Ctrl-6 there, but it happens if I do `:b 1`/`:b 2` as well.

**Comment by w0rp** [comment]
I tried switching buffers with `:b`, `:e`, and various other commands, and I can't repeat the bug. Are you using the latest code?

**Comment by trygveaa** [comment]
I am using the latest version, but I tested with an empy vimrc now. It seems that this only happens if `hidden` is set. Without that the markers are gone after switching file.

**Comment by k33nice** [comment]
I have the same bug, but only in golang porjects (it reproduced without ```hidden```), I tried to repeat it in js with and without ```hidden```, but unsuccessfully. Maybe it's specific for some linters (for js i use only eslint).

**Comment by w0rp** [comment]
Aha, `hidden` has to be set. That's why I didn't see it.

**Comment by w0rp** [comment]
I almost fixed this, apart from one test issue. I'll see if I can push a commit tomorrow.

**Comment by trygveaa** [comment]
Nice, thanks. Did you fix it so the highlights are remembered for each file, like the gutter markers?

**Comment by w0rp** [comment]
Highlights can't be associated with a particular buffer (unless you use the NeoVim-only API), but they can be removed and added again. I was able to set it up so highlights are removed when buffers are hidden and added back again when they are shown. I just need to fix a test issue for testing that.

**Comment by w0rp** [comment]
I have fixed this now. Now matches will be saved, cleared, and then restored when buffers are hidden and shown.

**Comment by trygveaa** [comment]
Thanks for the quick fix!

**Comment by k33nice** [comment]
It seems like bug still reproduces for golang
![ale](https://cloud.githubusercontent.com/assets/7413677/25694100/8b9e86c6-30b5-11e7-8f91-35ca3858049b.gif)

**Comment by w0rp** [comment]
That's a separate issue. I'll have a look at that. I fixed the highlights, and not the signs. I thought the signs were okay.

**Comment by trygveaa** [comment]
Yeah, that's a separate issue. The issue I reported is fixed, I didn't experience any problems with the signs.

**Comment by k33nice** [comment]
Thanks! I'd commented here cuz thought it has same nature.

**Comment by k33nice** [comment]
Just to be clear, this bug reproduces only in **go**. Also, it **"go build"** linter problem. And I found commit after after which it's began 0b4acd645395d4196f2e346d65aeddf063927f4e.

For repeat the bug:
1. Install go
2. Clone repo https://github.com/k33nice/ale-go
3. Nothing need in vimrc except ale
4. Open files (foo.go has error, bar.go - no)
5. Doesn't matter how to switch buffers

**Comment by w0rp** [comment]
Thank you for adding the repository. I'll check this out later.

**Comment by blockloop** [comment]
I think I'm getting a similar error related to this one. I am seeing errors for other files. For example, I'm seeing an error that says "err shadows declaration sql_helpers.go" when I am in "sql.go", a completely different file. Is this related?
